services:
  app:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env  # This loads the environment variables from the .env file
    environment:
      DATABASE_URL: postgres://postgres:password@db/permieportal_dev   # Explicitly define database URL here
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails s -b '0.0.0.0'"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

