version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "./storage:/app/storage"
      - "./public/assets:/app/public/assets"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: permieportal_dev
      DATABASE_URL: "postgres://postgres:password@db:5432/permieportal_dev"
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      if ! rails db:version > /dev/null 2>&1; then rails db:create; fi &&
      rails db:migrate &&
      rails db:seed &&
      rails server -b 0.0.0.0"
      
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: permieportal_dev
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  db_data:
    driver: local
