services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "./storage:/app/storage"
      - "./public/assets:/app/public/assets"  # ✅ Ensure asset persistence
      - "./public/builds:/app/public/builds"  # ✅ Persist Tailwind builds
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      if ! rails db:version > /dev/null 2>&1; then rails db:create; fi &&
      rails db:migrate &&
      rails db:seed &&
      rails server -b 0.0.0.0"
      
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"  # Remove this if you don't need external access
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
    driver: local
