services:
  app:
    build: .
    volumes:
      - ".:/app"  # Mount the application code from the host
    ports:
      - "3000:3000"  # Expose port 3000 for the Rails app
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from the .env file
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails s -b '0.0.0.0'
      "

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data  # Explicitly set the PostgreSQL data directory
    ports:
      - "5432:5432"  # Map database port for external access (if needed)
    volumes:
      - db_data:/var/lib/postgresql/data  # Use named volume for database storage
    restart: always  # Ensure the database container restarts on failure or host reboot

volumes:
  db_data:
    driver: local
