services:
  app:
    build: .
    volumes:
      - ".:/app"  # Mount the application code from the host
    ports:
      - "3000:3000"  # Expose port 3000 for the Rails app
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      DATABASE_URL: postgres://postgres:password@db/permieportal_dev  # Explicitly define database URL here
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails s -b '0.0.0.0'
      "

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}  # Default user if not defined in .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}  # Default password if not defined in .env
      POSTGRES_DB: ${POSTGRES_DB:-permieportal_dev}  # Default database name if not defined in .env
      PGDATA: /var/lib/postgresql/data  # Explicitly set the PostgreSQL data directory
    volumes:
      - db_data:/var/lib/postgresql/data  # Use named volume for database storage
    restart: always  # Ensure the database container restarts on failure or host reboot

volumes:
  db_data:
    driver: local

