default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permieportal_dev
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: permieportal_test
  host: db
  username: postgres
  password: password

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

