default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permieportal_dev
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: <%= ENV['TEST_POSTGRES_DB'] || 'permieportal_test' %>
  username: <%= ENV['TEST_POSTGRES_USER'] %>
  password: <%= ENV['TEST_POSTGRES_PASSWORD'] %>
  host: <%= ENV['TEST_DATABASE_HOST'] %>
  port: <%= ENV['TEST_DATABASE_PORT'] || 5432 %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>