default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permieportal_dev
  host: db
  username: postgres
  password: password

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>



production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
