development:
  service: Disk
  root: <%= Rails.root.join("storage") %>  # Local storage path

production:
service: Disk
  root: <%= Rails.root.join("storage") %>



# Add the local storage service to avoid errors for local file access in development
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

